[package]
name = "rank"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
lto = "t"
panic = "abort"
strip = true
[dependencies]
logos = "0.12.1"